bbs/urls.py
from django.urls import path
from . import views

app_name = "bbs"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/update/", views.DetailView.as_view(), name="update"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("bbs/", include("bbs.urls")),
    path("hello/", include("hello.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", RedirectView.as_view(url="/bbs/")),
]

hello/urls.py
from django.urls import path
from . import views

app_name = "hello"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index")
]

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Article(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.content
    
    def get_absolute_url(self):
        return reverse("bbs:detail", kwargs={"pk":self.pk})
    

hello/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

bbs/views.py
from django.shortcuts import render
from django.views import generic
from .models import Article

# Create your views here.

class IndexView(generic.ListView):
    model = Article
    template_name = "bbs/index.html"
    
class DetailView(generic.DetailView):
    model = Article
    template_name = "bbs/detail.html"

class CreateView(generic.edit.CreateView):
    model = Article
    template_name = "bbs/create.html"
    fields = "__all__"
    
class UpdateView(generic.edit.UpdateView):
    model = Article
    template_name = "bbs/create.html"
    fields = "__all__"
    
    

hello/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render
from .models import Article
from django.views import generic

class IndexView(generic.ListView):
    model = Article
    template_name = "hello/index.html"

templates/bbs/create.html
{% extends "base.html" %}<!-- 共通テンプレートの呼び出し -->
{% load django_bootstrap5 %}<!--django-bootstrap5のカスタムテンプレートタグの読み込み-->

{% block content %}
    <h1>投稿の{{object|yesno:"編集、新規作成"}}</h1><!--新規と編集で表示を変更-->>
    <form actiom="" method="post">{% csrf_token %}
        {{ form.as_p }}<!--すべての項目を表示-->>
        <button type="submit">{{object|yesno:"更新、作成"}}</button>
    </form>

    <div>
        <button onclick="JavaScript:history.back()">戻る</button>
    </div>

{% endblock %}

templates/bbs/detail.html
{% extends "base.html" %}<!-- 共通テンプレートの呼び出し -->
{% load django_bootstrap5 %}<!--django-bootstrap5のカスタムテンプレートタグの読み込み-->

{% block content %}
    <h1>{{article.id}}の詳細投稿ページ</h1>
    <div class="container">
        <p>{{ article.id }}:{{ article.author }}:{{ article.created_at }}</p>
        <p>最終更新:{{ article.updated_at}}</p><!--追記-->>
        <p>{{ article.content }}</p>
        <p><a href='{% url "bbs:update" article.pk %}'></a></p>
    </div>
        <p><a href='{% url "bbs:index" %}'>   
        </a></p>

{% endblock %}

    

templates/bbs/index.html
{% extends "base.html" %}<!--共通テンプレートの呼び出し-->
{% load django_bootstrap5 %}<!--django-bootstrap5のカスタムテンプレートタグの読み込み-->

    {% block content %}
        <h1 class=""mt-5>CRUDアプリを作ってみよう</h1>
        {% for article in object_list %}
            <div class="card bg-light shadow-sm mt-3">
                <div class="card-body">
                    <p>{{ article.id }}:{{ article.author }}:{{ article.created_at }}</p>
                    <p><a href='{% url "bbs:detail" article.id %}'>
                        {{ article.content }}</a></p>
                </div>
            </div>
        {% endfor %}
        <!--新規投稿ページへのリンク-->
        <div class="mt-3">
            <a href="{% url 'bbs:create' %}">
                {% bootstrap_button button_type="submit" content="新規投稿" size="md" %}
            </a>
        </div>   
    {% endblock %}

    

templates/hello/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Djangoを使ってみよう!</title>
    </head>
    <body>
        <h1>クラスベースの汎用ビュー</h1>
        {% for article in object_list %}
            <p>{{article.content }}</p>
        {% endfor %}

    </body>
</html>